___
# Atividade: Variáveis aleatórias discretas
___

## Aula 10

<div id="indice"></div>

## Índice

- [Corretora de Seguros](#corretora-de-seguros)
    - [Exercício 1](#ex1)
    - [Exercício 2](#ex2)
    - [Exercício 3](#ex3)
    - [Exercício 4](#ex4)
    - [Exercício 5](#ex5)
    - [Exercício 6](#ex6)


In [2]:
import numpy as np
import random
import pandas as pd

___

<div id="corretora-de-seguros"></div>

## Corretora de Seguros

Uma corretora de seguros paga uma comissão de R\\$50,00 a cada novo seguro que um corretor vende. A probabilidade de um cliente adquirir o seguro é de 0,20. 

1. Descreva como pode se comportar a comissão se um corretor ao abordar 2 clientes de maneira independente um do outro.
1. Qual a probabilidade de um corretor ganhar apenas R\\$50,00?

Vamos considerar os eventos:

- $S_i$: o cliente $i$ compra o seguro;
- $N_i = S_i^C$: o cliente $i$ não compra o seguro.

Pelo enunciado sabemos que:

- $P(S_i) = 0.2$
- $P(N_i) = P(S_i^C) = 1 - P(S_i) = 0.8$

Listando todas as possíveis combinações de eventos, temos:

Cliente 1 | Cliente 2 | Probabilidade           | Valor da comissão
--------- | --------- | ----------------------- | -----------------
$N_1$     | $N_2$     | $P(N_1)P(N_2)$ = $0.64$ | 0
$N_1$     | $S_2$     | $P(N_1)P(S_2)$ = $0.16$ | 50
$S_1$     | $N_2$     | $P(S_1)P(N_2)$ = $0.16$ | 50
$S_1$     | $S_2$     | $P(S_1)P(S_2)$ = $0.04$ | 100

Estamos interessados no valor da comissão de um corretor. Para isso, vamos definir a variável aleatória:

- $C$: valor da comissão do corretor.

Assim, o item 2 pode ser interpretado como: qual é o valor de $P(C=50)$?

Consultando a tabela calculada acima, vemos que $P(C=50) = 0.16 + 0.16 = 0.32$.

<div id="ex1"></div>

### EXERCÍCIO 1

Calcule o valor esperado e a variância da variável $C$.

*Resposta esperada para esperança e variância respectivamente: 20.0 reais ; 800.0 reais^2*

In [8]:
# ESCREVA SEU CÓDIGO AQUI
media = 0.64*0+0.16*50+0.16*50+0.04*100
print(media)
var = (((0-media)**2) * 0.64)+(((50-media)**2) * 0.16)+(((50-media)**2) * 0.16)+(((100-media)**2) * 0.04)
print(var)


20.0
800.0


___
## Tomando uma decisão

Imagine que a corretora de seguros irá fornecer um aumento na comissão dos corretores. Entretanto, cada corretor poderá escolher uma das seguintes opções:

- **Opção 1:** Nova comissão será a comissão atual mais um fixo de R$ 20,00;
- **Opção 2:** Nova comissão será o dobro da atual comissão.

<br>

A ideia aqui é fazer uma escolha de qual delas é melhor para aumentar o ganho de um corretor. 

Para isso, resolva os exercícios a seguir para auxiliá-lo nessa escolha.

<div id="ex2"></div>

### EXERCÍCIO 2

Construa a distribuição de probabilidade para cada uma das opções.


ESCREVA SUA RESPOSTA AQUI

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

In [14]:
PNN = 0.64
PNS = 0.16
PSN = 0.16
PSS = 0.04

<div id="ex3"></div>

### EXERCÍCIO 3

Considerando as respectivas distribuições de probabilidades, calcule o valor esperado e a variância para cada opção. 

In [37]:
# ESCREVA SEU CÓDIGO AQUI
o1_PNN=20
o1_PSN=70
o1_PNS=70
o1_PSS=120

OP1 = {PNN:o1_PNN, PSN:o1_PSN, PNS:o1_PNS, PSS:o1_PSS}

o2_PNN=0
o2_PSN=100
o2_PNS=100
o2_PSS=200

OP2 = {PNN:o2_PNN, PSN:o2_PSN, PNS:o2_PNS, PSS:o2_PSS}

media1 = PNN*o1_PNN+PNS*o1_PSN+PSN*o1_PNS+PSS*o1_PSS
var1 = (((o1_PNN-media1)**2) * PNN)+(((o1_PSN-media1)**2) * PNS)+(((o1_PNS-media1)**2) * PSN)+(((o1_PSS-media1)**2) * PSS)
media2 = PNN*o2_PNN+PNS*o2_PSN+PSN*o2_PNS+PSS*o2_PSS
var2 = (((o2_PNN-media2)**2) * PNN)+(((o2_PSN-media2)**2) * PNS)+(((o2_PNS-media2)**2) * PSN)+(((o2_PSS-media2)**2) * PSS)

print(media1,var1)
print(media2,var2)

40.0 800.0
40.0 3200.0


<div id="ex4"></div>

### EXERCÍCIO 4

Baseado nas propriedades da esperança (nos slides), calcule o valor esperado para a nova comissão em cada uma das opções.

*Resposta esperada para esperança opção 1 e 2 respectivamente: 40.0 reais ; 40.0 reais*

In [40]:
# ESCREVA SEU CÓDIGO AQUI
esp1=0
esp2=0

for prob, value in OP1.items():
    esp1 += value*prob
    
for prob, value in OP2.items():
    esp2 += value*prob

print(esp1)
print(esp2)

28.8
24.0


<div id="ex5"></div>

### EXERCÍCIO 5

Baseado nas propriedades da variância (nos slides), calcule a variância para a nova comissão em cada uma das opções.

*Resposta esperada para variância opção 1 e 2 respectivamente: 800.0 reais^2 ; 3200.0 reais^2*

In [ ]:
# ESCREVA SEU CÓDIGO AQUI

<div id="ex6"></div>

### EXERCÍCIO 6

Baseado nos resultados acima, qual opção você recomendaria para um corretor?

ESCREVA SUA RESPOSTA AQUI

# Referências

1. MONTGOMERY, D. et al. Estatística Aplicada e Probabilidade para Engenheiros. 6. ed. Seções 2.8 e 3.1
1. MAGALHÃES, M. et al. Noções de Probabilidade e Estatística. 7. ed. Seções 3.1 e definições 4.2 (p. 110) e 4.5 (p. 121)